codecov:
  # codecov.io should send its reports ASAP
  # https://docs.codecov.com/docs/codecovyml-reference#codecovrequire_ci_to_pass
  require_ci_to_pass: false
  notify:
    # codecov.io should send its reports ASAP
    # https://docs.codecov.com/docs/codecovyml-reference#codecovnotifywait_for_ci
    wait_for_ci: false
    after_n_builds: 2 # Only send notifications after 2 builds because we upload 2 times currently (1x PHPUnit / 1x Codeception)

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.01%
        paths:
          - "src/Snicco/*"
        if_not_found: failure
        # codecov.io should only care about its own status.
        # We don't want codecov.io to set its check to error if
        # let's say the commit message linting failed.
        if_ci_failed: success

    # The difference is explained quite vague at https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        target: auto
        threshold: 0.05%
        paths:
          - "src/Snicco/*"
        if_not_found: failure
        # codecov.io should only care about its own status.
        # We don't want codecov.io to set its check to error if
        # let's say the commit message linting failed.
        if_ci_failed: success

  precision: 3
  round: nearest
  range: "95...99"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
  require_head: true
  require_base: true
  after_n_builds: 2 # Only send notifications after 2 builds because we upload 2 times currently (1x PHPUnit / 1x Codeception)
