codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
    after_n_builds: 5 # Only send notifications after 5 builds because we upload 5 times currently (3x PHPUnit / 2x Codeception)

coverage:
  precision: 2
  round: down
  range: "90...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_head: yes
  require_base: yes
  after_n_builds: 5 # Only send notifications after 5 builds because we upload 5 times currently (3x PHPUnit / 2x Codeception)