name: Code Analysis

on:
  pull_request:
  push:

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:
  code_analysis:
    runs-on: ubuntu-20.04
    name: ${{ matrix.actions.name }}
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: 'Deptrac'
            run: |
              curl -LS https://github.com/qossmic/deptrac/releases/download/0.19.3/deptrac.phar -o deptrac.phar
              sudo chmod +x deptrac.phar
              sudo mv deptrac.phar /usr/local/bin/deptrac
              composer deptrac -- --formatter=github-actions

          - name: 'Composer Validate'
            run: composer validate


    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: 'Install dependencies'
        uses: ramsey/composer-install@v1

      - run: ${{ matrix.actions.run }}
